deps_config := \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/tuning/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/simulator/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/sdk/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/zealand/bluegrip/Kconfig.toolchain \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/zealand/bluegrip/app/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/zealand/bluegrip/Kconfig.drv \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/zealand/bluegrip/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/zealand/bluegrip/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/zealand/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/basictest/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/app/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/freertos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/Kconfig.debug \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/hifi3/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/cape2/demos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/cape2/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/cape2/rtos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/cape2/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/lle/demos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/lle/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/lle/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/asip/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/cape2/app/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/cape2/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/cape2/rtos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/cape2/etc/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/cape2/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/Kconfig.toolchain \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/test/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/app/spiaudio/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/app/pm/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/app/ctrl/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/app/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/rtos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/Kconfig.bootloader \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/m33/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/Kconfig.imgs \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/Kconfig.sec \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/tahiti/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/plugin/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/basictest/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/app/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/freertos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/Kconfig.debug \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/hifi4/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/Kconfig.toolchain \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/app/hid/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/app/ctrl/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/app/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/driver/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/rtos/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/m33/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/Kconfig.mem \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/niue/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/linux/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/apo/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/apps/SmartPlayer/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/apps/ConexantUSBTypeC2/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/apps/SmartRecorder/Kconfig.sensory \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/apps/SmartRecorder/Kconfig.asr \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/apps/SmartRecorder/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/apps/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/libeffects/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/android/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/Kconfig.add \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/platform/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/tmpl/cape2_code/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/sens//Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/lenovo/cape2_code/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/goog/cape2_code/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/cnxt/sw_code/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/cnxt/cape2_code/lle/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/cnxt/cape2_code/include/host/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/cnxt/cape2_code/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/Kconfig.add \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/libraries/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/host/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/golem/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/fcp/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/config/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/caf/Kconfig.segment \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/caf/Kconfig.control \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/caf/Kconfig.module \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/caf/Kconfig \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/Kconfig.add \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/caf/Kconfig.build.txt \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/Kconfig.components \
	/cygdrive/c/Jenkins/workspace/Build-Test-CAF-SW_cafbase/Kconfig

src/include/auto.conf: \
	$(deps_config)


$(deps_config):: ;
