#ifndef	_EXECUTOR_CFG_H_
#define	_EXECUTOR_CFG_H_

#define CONFIG_MAX_WORK_QUEUE_PER_CORE 4
#define CONFIG_MAX_NUM_CORES_PER_INFER  2   // Maximum number of cores used in a infer

#define CONFIG_EXEC_MAX_SCHEDULED_WORK  (((CONFIG_MAX_WORK_QUEUE_PER_CORE + 1) * CONFIG_MAX_NUM_CORES_PER_INFER) + 1)
#define CONFIG_EXEC_M33_TASK_STACK_SIZE          (768U)
#define CONFIG_EXEC_NPU_TASK_STACK_SIZE        (256U)
#define CONFIG_EXEC_CAPE_TASK_STACK_SIZE        (256U)

#define CONFIG_EXEC_M33_TASK_PRIORITY (OS_TASK_HIGHEST_PRIORITY - 1)
#define CONFIG_EXEC_NPU_TASK_PRIORITY (OS_TASK_HIGHEST_PRIORITY - 1)
#define CONFIG_EXEC_CAPE_TASK_PRIORITY (OS_TASK_HIGHEST_PRIORITY - 1)

#define CONFIG_EXEC_NPU_QUEUE_NUM_ELEMENTS CONFIG_MAX_WORK_QUEUE_PER_CORE
#define CONFIG_EXEC_CAPE_QUEUE_NUM_ELEMENTS CONFIG_MAX_WORK_QUEUE_PER_CORE
#define CONFIG_EXEC_M33_QUEUE_NUM_ELEMENTS   CONFIG_MAX_WORK_QUEUE_PER_CORE

//#define  CONFIG_TASK_NOTIFY   1
#define CONFIG_BIN_SEM              1
#endif /*_EXECUTOR_CFG_H_*/
